main/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'contributors', to: 'welcome#contributors'
  get 'diplom/:login/', to: 'welcome#diplom', as: 'diplom'
end

main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

main/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :permitted_params, only: [:contributors, :diplom]

  def index

  end

  def contributors
    @errors = []
    contrubutors_res = HTTParty.get("http://#{request.host}:4000/contributors/show/#{@permitted_params[:owner]}/#{@permitted_params[:repo]}/#{@permitted_params[:count]}")
    if contrubutors_res.success?
      json = JSON.parse(contrubutors_res.body)
      if json["contributors"]
        @contributors = json["contributors"]
      else
        @errors = {errors: json["errors"] }
      end
    else
      @errors = {errors: "Can`t resolve service" }
    end
  rescue => e
    @errors << [e.class.name, e.message]
  end

  def diplom
    diplom_res = HTTParty.get("http://#{request.host}:5000/diplom/show/#{@permitted_params[:login]}")
    send_data diplom_res,
              filename: "#{@permitted_params[:login]}.pdf",
              type: 'application/pdf',
              disposition: 'inline'
  rescue => e
    @errors = [[e.class.name, e.message]]
    render 'welcome/contributors'
  end

  private

    def permitted_params
      @permitted_params = params.permit(:repo, :count, :owner, :login).to_h
    end
end

main/app/helpers/application_helper.rb
module ApplicationHelper
end

main/app/helpers/welcome_helper.rb
module WelcomeHelper
end

main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Main</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

main/app/views/welcome/contributors.html.haml
.container
  .row
    %h1
      = "Contributors repository: \"#{@permitted_params[:repo]}\""
    .col-md-4
      - if @errors.empty?
        %ul
          - @contributors.each do |contributor|
            %li
              %p
                = contributor["login"]
              %p
                = link_to "Show diploma", diplom_path(login: contributor["login"]), class: "diploma_link"

      - else
        %ul
          - @errors.each do |msg|
            %li
              = msg

main/app/views/welcome/index.html.haml
.container
  .col-lg-4
    = form_tag contributors_path, method: 'get' do
      .row.column
        = label_tag "Repo name", :repo
        = text_field_tag :repo, nil, required: true, class: "form-control"
      .row.column
        = label_tag "Owner", :owner
        = text_field_tag :owner, nil, required: true, class: "form-control"
      .row.column
        = label_tag "Count number(max 30)", :count
        = number_field_tag :count, nil, required: true, class: "form-control", min:"1", step:"1"
      .row.column
        = submit_tag 'Show'